import Head from 'next/head'
import styles from '../styles/Home.module.css'
import SpeedTest from '../components/SpeedTest'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <SpeedTest />
      </main>

      <footer className={styles.footer}>
        © 2022 Arturo Vazquez
      </footer>
    </div>
  )
}
